%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-rviz-visual-tools
Version:        4.1.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rviz_visual_tools package

License:        BSD
URL:            https://github.com/PickNikRobotics/rviz_visual_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       qt5-qtbase
Requires:       ros-rolling-ament-index-python
Requires:       ros-rolling-eigen-stl-containers
Requires:       ros-rolling-eigen3-cmake-module
Requires:       ros-rolling-geometry-msgs
Requires:       ros-rolling-interactive-markers
Requires:       ros-rolling-launch
Requires:       ros-rolling-launch-ros
Requires:       ros-rolling-pluginlib
Requires:       ros-rolling-rclcpp
Requires:       ros-rolling-rclcpp-components
Requires:       ros-rolling-rviz-common
Requires:       ros-rolling-rviz-default-plugins
Requires:       ros-rolling-rviz-ogre-vendor
Requires:       ros-rolling-rviz-rendering
Requires:       ros-rolling-rviz2
Requires:       ros-rolling-sensor-msgs
Requires:       ros-rolling-shape-msgs
Requires:       ros-rolling-std-msgs
Requires:       ros-rolling-tf2
Requires:       ros-rolling-tf2-eigen
Requires:       ros-rolling-tf2-geometry-msgs
Requires:       ros-rolling-trajectory-msgs
Requires:       ros-rolling-visualization-msgs
Requires:       ros-rolling-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-rolling-ament-cmake
BuildRequires:  ros-rolling-eigen-stl-containers
BuildRequires:  ros-rolling-eigen3-cmake-module
BuildRequires:  ros-rolling-geometry-msgs
BuildRequires:  ros-rolling-interactive-markers
BuildRequires:  ros-rolling-pluginlib
BuildRequires:  ros-rolling-rclcpp
BuildRequires:  ros-rolling-rclcpp-components
BuildRequires:  ros-rolling-rviz-common
BuildRequires:  ros-rolling-rviz-default-plugins
BuildRequires:  ros-rolling-rviz-ogre-vendor
BuildRequires:  ros-rolling-rviz-rendering
BuildRequires:  ros-rolling-sensor-msgs
BuildRequires:  ros-rolling-shape-msgs
BuildRequires:  ros-rolling-std-msgs
BuildRequires:  ros-rolling-tf2
BuildRequires:  ros-rolling-tf2-eigen
BuildRequires:  ros-rolling-tf2-geometry-msgs
BuildRequires:  ros-rolling-trajectory-msgs
BuildRequires:  ros-rolling-visualization-msgs
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-rolling-ament-cmake-gtest
BuildRequires:  ros-rolling-ament-lint-auto
BuildRequires:  ros-rolling-ament-lint-common
%endif

%description
Utility functions for displaying and debugging data in Rviz via published
markers

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Thu Jan 05 2023 Mike Lautman <mike@picknik.ai> - 4.1.4-1
- Autogenerated by Bloom

* Tue Jul 19 2022 Mike Lautman <mike@picknik.ai> - 4.1.3-1
- Autogenerated by Bloom

* Tue Feb 08 2022 Mike Lautman <mike@picknik.ai> - 4.1.2-2
- Autogenerated by Bloom

