Name:           ros-melodic-rviz-visual-tools
Version:        3.8.0
Release:        3%{?dist}
Summary:        ROS rviz_visual_tools package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/davetcoleman/rviz_visual_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       ogre-devel
Requires:       qt5-qtx11extras-devel
Requires:       ros-melodic-eigen-conversions
Requires:       ros-melodic-eigen-stl-containers
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-graph-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-roslint
Requires:       ros-melodic-rviz
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf-conversions
Requires:       ros-melodic-trajectory-msgs
Requires:       ros-melodic-visualization-msgs
BuildRequires:  ogre-devel
BuildRequires:  qt5-qtx11extras-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-eigen-conversions
BuildRequires:  ros-melodic-eigen-stl-containers
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-graph-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-rviz
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf-conversions
BuildRequires:  ros-melodic-trajectory-msgs
BuildRequires:  ros-melodic-visualization-msgs

%description
Utility functions for displaying and debugging data in Rviz via published
markers

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Sep 18 2019 Dave Coleman <davetcoleman@gmail.com> - 3.8.0-3
- Autogenerated by Bloom

* Wed Sep 18 2019 Dave Coleman <davetcoleman@gmail.com> - 3.8.0-2
- Autogenerated by Bloom

* Wed Sep 18 2019 Dave Coleman <davetcoleman@gmail.com> - 3.8.0-1
- Autogenerated by Bloom

* Mon Nov 26 2018 Dave Coleman <davetcoleman@gmail.com> - 3.7.0-0
- Autogenerated by Bloom

* Thu May 31 2018 Dave Coleman <davetcoleman@gmail.com> - 3.6.1-0
- Autogenerated by Bloom

